GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/ji

###
DELETE http://localhost:3001/api/persons/64aa454181ab1a1d44264d2c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"chan2",
    "number":"01-551245ewgw55"
}

###
PUT http://localhost:3001/api/persons/64aa3c06e5ba4ae9defc4469
Content-Type: application/json

{
    "name":"Bi",
    "number":"011-5555555"
}

###
GET http://localhost:3001/api/randomendpoint